### PR TITLE
Fix: case for handling related ManyToMany extraction.

### PR DESCRIPTION
**Pull request by AlterEigo**
I had an issue with extraction of reverse ManyToMany relationship, and it seems like there simply was an unhandled case. I didn't really fix anything, I just copied your code from below and thus added another case. I didn't test this code with any automatic tool or unit tests, so beware. I'm rather new to python so feel free to do with it what you want. But please, if you don't pull - take at least the issue into account and do it your way :) I really appreciate your project and it saves our team a lot of time. Thank you.

### CODE REVIEW

**Comment by AlterEigo** [comment]
Trying to go further and analyze the code. I'll also try to add a unit test for it

**Comment by AlterEigo** [comment]
So it seems like there are cases when:
```python
field.concrete == True
field.auto_created == True
field.many_to_many == True
```
And this is exactly the case for certain fields of our models. At first I thought you handle all of  *ManyToMany* relations in the code below, in the `else` branch, but you only handle a part of it.

**Comment by jordaneremieff** [comment]
Hi @AlterEigo, thanks for the report, let's fix this.

Could you include a test case? Or if you include a minimal example of a model that can be used to reproduce the issue then I can take a look at it as well.

**Comment by AlterEigo** [comment]
Here you have our [django stacktrace](https://github.com/jordaneremieff/djantic/files/6808460/django_stacktrace.html.txt) (couldn't attach with `.html` extension, so just remove the `.txt` part).

As for the minimal example:
**models.py**:
```python
# Defining custom base class for all of our models
class ExtendedModel(models.Model)
    # some custom fields and other stuff
    class Meta:
        abstract = True    # Django won't create a table for this particular model

# Class with forward many-to-many relation
class Expert(ExtendedModel):
    # ... fields
    case = models.ManyToManyField("Case", related_name="related_experts", blank = True);

class Case(ExtendedModel):
    # ... some unrelated fields
    # 'related_experts' -> automatically generated by Django
    # In our case this field has: concrete == False, auto_created == True, many_to_many == True
```

I think that `related_experts.concrete` variable should be `True` since the `abstract` property is not inherited, and the Expert model **does** have a table for itself, unlike the ExtendedModel. But somehow the value is set to `False`.

**requirements.txt**:
```
asgiref==3.3.4
Django==3.2.2
djangorestframework==3.12.4
djantic==0.3.3
psycopg2-binary==2.8.6
pydantic==1.8.2
pytz==2021.1
sqlparse==0.4.1
typing-extensions==3.10.0.0
```

**Comment by jordaneremieff** [comment]
Thanks for sharing the example, I'll try to have a look at this sometime this week.

**Comment by jordaneremieff** [comment]
Hi @AlterEigo, 

I've merged the fix for this in https://github.com/jordaneremieff/djantic/pull/35 and have released it in version 0.3.4. Thanks for the initial report and example models, I've used them as the basis for the new tests.

Please open an issue if the changes in 0.3.4 do not resolve this for you.

**Comment by AlterEigo** [comment]
Perfect, I'll test it out on monday ;)
Thanks a lot

**Pull request closed without merging**
