### PR TITLE
Add support for: blank and null fields

### PR DESCRIPTION
**Pull request by phbernardes**
This PR, separated in 2 commits, aims to:
- Add support for TextChoices fields with blank=True
- Add support for fields with null=True and default value defined

### CODE REVIEW

**Comment by jordaneremieff** [comment]
Hi @phbernardes, I'm going to open/close to PR to see if it triggers the workflow to test this against the different versions.

**Comment by jordaneremieff** [comment]
Thanks!

**Comment by pedro-prose** [comment]
Thank you @jordaneremieff, can you create a new release with these modifications?

**Comment by jordaneremieff** [comment]
@pedro-prose sure, I'll do one this week.

**Pull request merged**
